recipe: default.v1

language: zh

pipeline:
  - name: "JiebaTokenizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "RegexFeaturizer"
#  - name: "LanguageModelFeaturizer"  bye bert, I don't need u anymore~
#    model_name: "bert"
#    model_weights: "bert-base-chinese"
  - name: "DIETClassifier"
    epochs: 500

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
