# build for action server (but there is no action yet)

FROM rasa/rasa-sdk:3.2.0

COPY requirements.txt ./
COPY actions/actions.py ./
COPY data ./data

USER root

RUN pip install -r requirements.txt

CMD ["start", "--actions", "actions"]
