name: Training and Testing Rasa
on: [push]
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: train and test
          uses: RasaHQ/rasa-train-test-gha@main
          with:
            requirements_file: "requirements.txt"
            test_type: nlu
            github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models