name: Training and Testing Rasa
on: [push]
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          requirements_file: requirements.txt
          data_validate: true
          rasa_train: true
          cross_validation: false
          rasa_test: true
          test_type: all
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload model
        if: startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models

  build-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    env:
      IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          if [[ $IS_PUSH_EVENT == "false" ]]
          then
            IMAGE_TAG=${{ github.head_ref }}
          else
            IMAGE_TAG=$(basename ${{ github.ref }})
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build rasa Docker image
        run: |
          docker build -f ./Dockerfile_rasa . \
            --tag igxnon/qqbot-rasa:$IMAGE_TAG
          mkdir -p images
          docker save -o ./images/docker-image.tar igxnon/qqbot-rasa:$IMAGE_TAG

      - name: Upload image
        uses: actions/upload-artifact@master
        with:
          name: docker-image
          path: images
